name: build

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install requirements
        run: |
          sudo apt-get install libcurl4-openssl-dev libmicrohttpd-dev
      - name: Configure
        run: |
          mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: Compile
        run: |
          cd build && cmake --build . -j $(nproc --all) --target admin-tool
      - uses: actions/upload-artifact@v3
        with:
          name: admin-tool-linux
          path: build/admin-tool

      - uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: true
          files: build/admin-tool
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
